/**
 * HILLWATER Data Context
 * Central State & Telemetry Provider
 * Nainital Demonstration Network
 *
 * Demo Orchestration — State Machine
 * -----------------------------------
 * The "Run Demo Scenario" button launches a state machine that
 * drives REAL backend scenario transitions. Each step advances when
 * ACTUAL backend telemetry (risk score / alert type) confirms the
 * expected condition has been reached — NOT by a fake timer.
 *
 * State machine:
 *   0/6 → (idle)
 *   1/6 → NORMAL         : Wait for risk to be LOW (< 30)
 *   2/6 → GRADUAL_PRESSURE_DETERIORATION : Wait for risk MODERATE (>= 35)
 *   3/6 → (same scenario) : Wait for EARLY_WARNING or HIGH_RISK alert
 *   4/6 → RAPID_PRESSURE_DETERIORATION  : Wait for HIGH/CRITICAL risk (>= 65)
 *   5/6 → INTERVENE      : Auto-fire intervention; advance immediately after confirmation
 *   6/6 → SYSTEM_RECOVERY : Wait for risk to drop back (< 45) — "Recovery"
 *   → Demo Complete
 */

import { createContext, useContext, useState, useEffect, useCallback, useRef } from 'react'
import { apiService } from '../services/api'
import { getHierarchy, NAINITAL_DEMO_ZONES } from '../utils/hierarchy'
import { calculateZoneRisk } from '../utils/riskEngine'

const DataContext = createContext()

export const useData = () => {
  const context = useContext(DataContext)
  if (!context) {
    throw new Error('useData must be used within DataProvider')
  }
  return context
}

// ─────────────────────────────────────────────────────────────
// Demo Scenario State Machine Config
// Scenarios must match the exact keys in backend/simulator/scenarios.js
// ─────────────────────────────────────────────────────────────
const DEMO_ZONE_ID = 'mallital'
const DEMO_DEVICE_ID = 'SIM-001'

const DEMO_STEPS = [
  // Step 1 — Normal Operation
  // Advance condition: backend Risk Engine reports riskLevel === 'LOW'
  // (Backend riskConfig.js band: score <= 30 → 'LOW')
  // React OBSERVES backend output — does NOT redefine the LOW boundary.
  {
    step: 1,
    label: 'Normal Operation',
    scenario: 'NORMAL',
    advanceWhen: ({ mallitalZone }) => {
      return mallitalZone?.riskLevel === 'LOW'
    },
    minTicksBeforeAdvance: 2,
  },

  // Step 2 — Pressure Deterioration begins
  // Advance condition: the backend Risk Engine's 'Pressure Trend' factor
  // already sets status to 'FALLING' or 'RAPID_DECLINE' (riskEngine.js lines 50–57).
  // React reads the factor status — does NOT replicate the trend calculation.
  {
    step: 2,
    label: 'Pressure Deterioration',
    scenario: 'GRADUAL_PRESSURE_DETERIORATION',
    advanceWhen: ({ mallitalZone }) => {
      if (!mallitalZone?.factors) return false
      const trendFactor = mallitalZone.factors.find(f => f.name === 'Pressure Trend')
      return (
        trendFactor?.status === 'FALLING' ||
        trendFactor?.status === 'RAPID_DECLINE' ||
        trendFactor?.status === 'CRITICAL_DROP'
      )
    },
    minTicksBeforeAdvance: 1,
  },

  // Step 3 — Early Warning generated by backend Alert Engine
  // Advance condition: backend Alert Engine has created an EARLY_WARNING alert for Mallital.
  // This is already backend-driven — no change needed.
  {
    step: 3,
    label: 'Early Warning',
    scenario: null, // keep current scenario running
    advanceWhen: ({ alerts }) => {
      return alerts.some(
        a => a.zoneId === DEMO_ZONE_ID &&
          ['EARLY_WARNING', 'HIGH_RISK', 'RISK_ESCALATION', 'RAPID_DETERIORATION'].includes(a.type)
      )
    },
    minTicksBeforeAdvance: 1,
  },

  // Step 4 — High Risk / Critical
  // Advance condition: backend Risk Engine reports riskLevel === 'HIGH' or 'CRITICAL'
  // (Backend riskConfig.js bands: 61–80 → 'HIGH', 81–100 → 'CRITICAL')
  // React OBSERVES the riskLevel string — does NOT redefine the band boundaries.
  {
    step: 4,
    label: 'High Risk Detected',
    scenario: 'RAPID_PRESSURE_DETERIORATION',
    advanceWhen: ({ mallitalZone, alerts }) => {
      const isHighRisk =
        mallitalZone?.riskLevel === 'HIGH' ||
        mallitalZone?.riskLevel === 'CRITICAL'
      // Also accept if the Alert Engine has already fired a high/critical alert
      const hasHighAlert = alerts.some(
        a => a.zoneId === DEMO_ZONE_ID &&
          ['HIGH_RISK', 'CRITICAL_RISK', 'RISK_ESCALATION', 'RAPID_DETERIORATION'].includes(a.type)
      )
      return isHighRisk || hasHighAlert
    },
    minTicksBeforeAdvance: 1,
  },

  // Step 5 — Automated Intervention
  // Advance condition: intervention POST was confirmed successful by the backend
  // (response.success === true AND response.intervention.id exists).
  // Set via interventionAppliedRef in the special handler below.
  {
    step: 5,
    label: 'Intervention',
    scenario: null, // intervention + scenario switch handled in the special handler
    advanceWhen: ({ interventionApplied }) => interventionApplied === true,
    minTicksBeforeAdvance: 0,
  },

  // Step 6 — System Recovery
  // Advance condition: backend Alert Engine produces a 'RECOVERY' alert for Mallital
  // AFTER the intervention was confirmed. This guards against stale RECOVERY alerts
  // that may have been generated earlier in the demo (e.g., brief pressure recovery
  // during the GRADUAL_PRESSURE_DETERIORATION phase).
  // React does NOT define what counts as recovery — it waits for the backend event.
  {
    step: 6,
    label: 'Recovery',
    scenario: 'SYSTEM_RECOVERY',
    advanceWhen: ({ alerts, interventionTimestamp }) => {
      if (!interventionTimestamp) return false
      return alerts.some(
        a =>
          a.zoneId === DEMO_ZONE_ID &&
          a.type === 'RECOVERY' &&
          new Date(a.timestamp) > interventionTimestamp
      )
    },
    minTicksBeforeAdvance: 2,
  },
]

export const DataProvider = ({ children }) => {
  const [selectedTalukas] = useState(NAINITAL_DEMO_ZONES)

  // Demo Scenario State
  const [demoStep, setDemoStep] = useState(0)
  const [demoMessage, setDemoMessage] = useState('')
  const [demoComplete, setDemoComplete] = useState(false)

  // Core Data States
  const [zones, setZones] = useState([])
  const [alerts, setAlerts] = useState([])
  const [systemMetrics, setSystemMetrics] = useState({
    health: 'N/A',
    healthTrend: 'N/A',
    activeZones: 0,
    criticalZones: 0,
    warningCount: 0,
    activeAlerts: 0,
    avgPressure: 'N/A',
    totalFlow: 'N/A',
    totalDemand: 'N/A',
    tankAvailability: 'N/A',
    pressureStability: 'N/A',
    flowConsistency: 'N/A',
    systemStatus: 'INITIALIZING'
  })
  
  const [isConnected, setIsConnected] = useState(false)
  const [lastUpdate, setLastUpdate] = useState(() => new Date())
  const [simulatorStatus, setSimulatorStatus] = useState({ running: false, scenario: 'UNKNOWN' })
  
  const [logs, setLogs] = useState([
    {
      id: 'log-init-1',
      action: 'HillWater Telemetry Engine initialized — Live Polling Enabled',
      zone: 'SYSTEM',
      timestamp: new Date().toLocaleTimeString(),
      user: 'Network Operations Officer',
      type: 'System',
    }
  ])

  // ── Demo State Machine Internal State ──────────────────────
  // Using refs to avoid stale closure issues inside the polling loop
  const demoStepRef = useRef(0)               // current step (0 = idle, 1–6 = active)
  const demoTickCount = useRef(0)             // ticks spent waiting in current step
  const interventionAppliedRef = useRef(false)    // has step-5 intervention been confirmed?
  const interventionTimestampRef = useRef(null)   // Date of confirmed intervention (for Step 6)
  const demoActiveRef = useRef(false)         // is the demo currently running?

  // Helper to add audit logs
  const addLog = useCallback((action, zone = 'SYSTEM', metadata = {}) => {
    const now = new Date()
    const timestamp = now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' })

    const newLog = {
      id: `log-${Date.now()}-${Math.random().toString(36).substring(2, 7)}`,
      action,
      zone: zone || 'Network-wide',
      timestamp,
      user: metadata.user || 'Network Operations Officer',
      type: metadata.type || 'Operational',
      hierarchy: metadata.hierarchy || null,
      isAlertAck: metadata.isAlertAck || false,
    }
    setLogs(prev => [newLog, ...prev].slice(0, 100))
  }, [])

  // Map Backend Response to Frontend Zone shape
  const normalizeBackendZone = (zoneBase, latestReading, riskData, explanation, backendAlerts) => {
    const pressure = latestReading?.pressure !== undefined ? Number(latestReading.pressure) : 'N/A'
    const flow = latestReading?.flow !== undefined ? Number(latestReading.flow) : 'N/A'
    const tankLevel = latestReading?.tankLevel !== undefined ? Number(latestReading.tankLevel) : 'N/A'

    const likelyCauses = []
    if (explanation && explanation.primaryCause) {
      likelyCauses.push({
        cause: explanation.primaryCause.label,
        percentage: explanation.primaryCause.confidence || 90,
        detail: explanation.primaryCause.type
      })
    }

    const activeAlertsForZone = backendAlerts.filter(a => a.zoneId === zoneBase.id && !a.resolved)

    return {
      id: zoneBase.id,
      name: zoneBase.name,
      elevation: zoneBase.elevation || 'N/A',
      pressure: pressure,
      targetPressure: zoneBase.baselinePressure || 'N/A',
      flow: flow,
      demand: zoneBase.demand || 'N/A',
      tankLevel: tankLevel,
      tankCapacity: zoneBase.capacity || 'N/A',
      riskScore: riskData?.score !== undefined ? riskData.score : 'N/A',
      riskLevel: riskData?.level || 'LOW',
      factors: riskData?.factors || [],
      likelyCauses: likelyCauses,
      recommendation: explanation?.recommendation?.action || 'No action needed',
      alerts: activeAlertsForZone
    }
  }

  // ── Demo State Machine Tick ─────────────────────────────────
  // Called every polling cycle when demo is active.
  // Receives the latest mapped zones and alerts as context.
  const tickDemoStateMachine = useCallback(async (mappedZones, backendAlerts) => {
    if (!demoActiveRef.current) return

    const currentStep = demoStepRef.current
    if (currentStep === 0 || currentStep > DEMO_STEPS.length) return

    const stepConfig = DEMO_STEPS[currentStep - 1]
    const mallitalZone = mappedZones.find(z => z.id === DEMO_ZONE_ID)

    demoTickCount.current += 1
    const ticksWaited = demoTickCount.current

    const context = {
      mallitalZone,
      alerts: backendAlerts,
      interventionApplied: interventionAppliedRef.current,
      interventionTimestamp: interventionTimestampRef.current
    }

    // Special handling: Step 5 fires the intervention automatically.
    // IMPORTANT: interventionAppliedRef is only set to true AFTER:
    //   1. The API call returns success === true
    //   2. The response includes a confirmed intervention.id (backend audit trail entry)
    // Step 5 does NOT advance merely because the request was attempted.
    if (currentStep === 5 && !interventionAppliedRef.current) {
      try {
        const interventionRes = await apiService.interveneZone(DEMO_ZONE_ID, {
          interventionType: 'PRESSURE_SETPOINT',
          action: 'Emergency pressure setpoint adjustment — AI-initiated intervention',
          reason: 'High/Critical risk detected by HillWater predictive engine.',
          operator: 'HillWater AutoSystem'
        })

        // Verify backend confirmed the intervention (success + audit trail ID)
        const confirmed =
          interventionRes?.success === true &&
          typeof interventionRes?.intervention?.id === 'string'

        if (!confirmed) {
          console.error('Demo Step 5: Backend did not confirm intervention — will retry next tick.', interventionRes)
          return
        }

        // Only after confirmed: switch simulator to SYSTEM_RECOVERY
        await apiService.setSimulatorScenario('SYSTEM_RECOVERY')

        // Mark intervention as successfully applied, record exact confirmation timestamp
        interventionTimestampRef.current = new Date()
        interventionAppliedRef.current = true

        addLog(
          `DEMO: Intervention confirmed by backend (id: ${interventionRes.intervention.id}) — SYSTEM_RECOVERY initiated on Mallital`,
          'Mallital',
          { type: 'Intervention', user: 'HillWater AutoSystem' }
        )
      } catch (err) {
        console.error('Demo Step 5 intervention request failed:', err)
      }
      return // Wait for next tick — advanceWhen checks interventionAppliedRef
    }

    const shouldAdvance =
      ticksWaited > stepConfig.minTicksBeforeAdvance &&
      stepConfig.advanceWhen(context)

    if (!shouldAdvance) return

    // ── Advance to next step ──────────────────────────────────
    const nextStep = currentStep + 1

    if (nextStep > DEMO_STEPS.length) {
      // Demo Complete
      demoActiveRef.current = false
      demoStepRef.current = 0
      setDemoStep(0)
      setDemoComplete(true)
      setDemoMessage('Demo Complete')
      addLog('DEMO: All 6 steps completed successfully — Demo finished.', 'SYSTEM', { type: 'System' })
      return
    }

    const nextStepConfig = DEMO_STEPS[nextStep - 1]

    // Switch scenario if needed
    if (nextStepConfig.scenario) {
      try {
        if (nextStep === 1) {
          // First step — start the simulator
          await apiService.startSimulator(DEMO_ZONE_ID, DEMO_DEVICE_ID, nextStepConfig.scenario)
        } else {
          await apiService.setSimulatorScenario(nextStepConfig.scenario)
        }
        addLog(
          `DEMO: Step ${nextStep}/6 — ${nextStepConfig.label} (scenario: ${nextStepConfig.scenario})`,
          'Mallital',
          { type: 'System', user: 'HillWater Demo Orchestrator' }
        )
      } catch (err) {
        console.error(`Demo: Failed to set scenario for step ${nextStep}:`, err)
      }
    } else {
      addLog(
        `DEMO: Step ${nextStep}/6 — ${nextStepConfig.label} (monitoring in progress)`,
        'Mallital',
        { type: 'System', user: 'HillWater Demo Orchestrator' }
      )
    }

    demoStepRef.current = nextStep
    demoTickCount.current = 0
    setDemoStep(nextStep)
    setDemoMessage(nextStepConfig.label)
  }, [addLog])

  // Unified Polling Loop
  useEffect(() => {
    let pollingInterval = null
    let isPolling = false

    const pollBackend = async () => {
      if (isPolling) return
      isPolling = true

      try {
        // Step 1: Base requests
        const [healthRes, zonesRes, alertsRes, simRes] = await Promise.all([
          apiService.getHealth().catch(() => ({ success: false })),
          apiService.getZones().catch(() => ({ success: false })),
          apiService.getAlerts().catch(() => ({ success: false, alerts: [] })),
          apiService.getSimulatorStatus().catch(() => ({ success: false, running: false, scenario: 'UNKNOWN' }))
        ])

        if (healthRes.success) {
          setIsConnected(true)
          setSimulatorStatus({ running: simRes.running, scenario: simRes.scenario })
          const backendAlerts = alertsRes.success ? alertsRes.alerts : []
          
          let mappedZones = []
          
          if (zonesRes.success && zonesRes.zones) {
            // Step 2: Fetch detailed telemetry for each zone
            const detailedPromises = zonesRes.zones.map(async (zone) => {
              const [detailsRes, riskRes] = await Promise.all([
                apiService.getZone(zone.id).catch(() => null),
                apiService.getZoneRisk(zone.id).catch(() => null)
              ])
              return { 
                zoneBase: zone, 
                latestReading: detailsRes?.latestReading,
                riskData: riskRes?.risk,
                explanation: riskRes?.explanation
              }
            })

            const allDetails = await Promise.all(detailedPromises)
            mappedZones = allDetails.map(d => 
              normalizeBackendZone(d.zoneBase, d.latestReading, d.riskData, d.explanation, backendAlerts)
            )
          }

          setZones(mappedZones)
          setAlerts(backendAlerts)
          
          // Compute Derived Metrics safely
          const validScores = mappedZones.filter(z => typeof z.riskScore === 'number').map(z => z.riskScore)
          const avgScore = validScores.length ? validScores.reduce((a,b) => a+b,0)/validScores.length : 0
          
          const validPressures = mappedZones.filter(z => typeof z.pressure === 'number').map(z => z.pressure)
          const avgPressure = validPressures.length ? (validPressures.reduce((a,b) => a+b,0)/validPressures.length).toFixed(1) : 'N/A'

          const validFlows = mappedZones.filter(z => typeof z.flow === 'number').map(z => z.flow)
          const totalFlow = validFlows.length ? validFlows.reduce((a,b) => a+b,0) : 'N/A'

          const validDemands = mappedZones.filter(z => typeof z.demand === 'number').map(z => z.demand)
          const totalDemand = validDemands.length ? validDemands.reduce((a,b) => a+b,0) : 'N/A'

          const validTanks = mappedZones.filter(z => typeof z.tankLevel === 'number').map(z => z.tankLevel)
          const tankAvg = validTanks.length ? Math.round(validTanks.reduce((a,b) => a+b,0)/validTanks.length) : 'N/A'

          setSystemMetrics({
            health: Math.max(0, 100 - Math.round(avgScore)),
            healthTrend: 'N/A',
            activeZones: mappedZones.length,
            criticalZones: mappedZones.filter(z => z.riskLevel === 'CRITICAL').length,
            warningCount: mappedZones.filter(z => z.riskLevel === 'HIGH').length,
            activeAlerts: backendAlerts.filter(a => !a.resolved).length,
            avgPressure: avgPressure,
            totalFlow: totalFlow,
            totalDemand: totalDemand,
            tankAvailability: tankAvg,
            pressureStability: 'N/A',
            flowConsistency: 'N/A',
            systemStatus: 'ONLINE'
          })
          
          setLastUpdate(new Date())

          // ── Tick the Demo State Machine ─────────────────────
          if (demoActiveRef.current) {
            await tickDemoStateMachine(mappedZones, backendAlerts)
          }
        } else {
          setIsConnected(false)
          setSystemMetrics(prev => ({ ...prev, systemStatus: 'OFFLINE' }))
        }
      } catch (error) {
        console.error('Telemetry Polling Error:', error)
        setIsConnected(false)
        setSystemMetrics(prev => ({ ...prev, systemStatus: 'OFFLINE' }))
      } finally {
        isPolling = false
      }
    }

    // Initial fetch
    pollBackend()

    // Start 3000ms polling cycle
    pollingInterval = setInterval(pollBackend, 3000)

    return () => {
      if (pollingInterval) clearInterval(pollingInterval)
    }
  }, [tickDemoStateMachine])


  // Interactive What-If Simulation Apply Function (Local UI logic preserved)
  const applyZoneIntervention = useCallback((zoneId, interventionType, magnitude) => {
    setZones(prevZones => {
      const updated = prevZones.map(z => {
        if (z.id === zoneId || z.name === zoneId) {
          // Note: using local mock engine for WHAT IF
          const simulatedAnalysis = calculateZoneRisk({
            ...z,
            intervention: { type: interventionType, magnitude: Number(magnitude) }
          })
          return {
            ...z,
            pressure: simulatedAnalysis.effectivePressure,
            riskScore: simulatedAnalysis.riskScore,
            riskLevel: simulatedAnalysis.riskLevel,
            factors: simulatedAnalysis.factors,
            likelyCauses: simulatedAnalysis.likelyCauses,
            recommendation: simulatedAnalysis.recommendation,
          }
        }
        return z
      })
      return updated
    })

    const targetZone = zones.find(z => z.id === zoneId || z.name === zoneId)?.name || zoneId || 'Network-wide'
    addLog(`Simulated Intervention applied on ${targetZone}: ${interventionType} (${magnitude > 0 ? '+' : ''}${magnitude}%)`, targetZone, {
      type: 'Simulation'
    })
  }, [addLog, zones])

  // ── Run Demo Scenario ──────────────────────────────────────
  // 1. Reset backend state
  // 2. Activate the demo state machine at step 1
  // 3. Start the simulator on NORMAL
  // The state machine will handle all subsequent transitions
  const runDemoScenario = useCallback(async () => {
    try {
      // Reset backend in-memory state for a clean demo
      await apiService.resetDemo().catch(err => console.warn('Demo reset failed (non-fatal):', err.message))

      // Reset internal demo state machine refs
      demoActiveRef.current = true
      demoStepRef.current = 1
      demoTickCount.current = 0
      interventionAppliedRef.current = false
      interventionTimestampRef.current = null

      // Update UI state
      setDemoStep(1)
      setDemoComplete(false)
      setDemoMessage('Normal Operation')

      // Start the simulator on NORMAL scenario
      await apiService.startSimulator(DEMO_ZONE_ID, DEMO_DEVICE_ID, 'NORMAL')

      addLog(
        'DEMO: Step 1/6 — Normal Operation started. State machine active.',
        'Mallital',
        { type: 'System', user: 'HillWater Demo Orchestrator' }
      )
    } catch (error) {
      console.error('runDemoScenario error:', error)
      addLog('Demo Scenario Failed to Start — check backend connectivity', 'SYSTEM', { type: 'System' })
      demoActiveRef.current = false
      demoStepRef.current = 0
      setDemoStep(0)
    }
  }, [addLog])

  // ── Stop Demo Scenario ─────────────────────────────────────
  const stopDemoScenario = useCallback(async () => {
    try {
      demoActiveRef.current = false
      demoStepRef.current = 0
      demoTickCount.current = 0
      interventionAppliedRef.current = false
      interventionTimestampRef.current = null

      setDemoStep(0)
      setDemoMessage('')
      setDemoComplete(false)

      await apiService.stopSimulator()
      addLog('Demo Scenario stopped by operator.', 'SYSTEM', { type: 'System' })
    } catch (error) {
      console.error('stopDemoScenario error:', error)
    }
  }, [addLog])

  const acknowledgeAlert = async (alertId) => {
    try {
      await apiService.acknowledgeAlert(alertId)
      
      const alertToAck = alerts.find(a => a.id === alertId)
      if (alertToAck) {
        const hierarchy = getHierarchy(alertToAck.zoneId || alertToAck.zoneName)
        addLog(`Acknowledged Alert: ${alertToAck.title}`, alertToAck.zoneName || hierarchy.zoneName || 'Network-wide', {
          type: alertToAck.severity,
          hierarchy: hierarchy.fullPath,
          isAlertAck: true,
        })
      }
      
      setAlerts(prev =>
        prev.map(alert =>
          alert.id === alertId ? { ...alert, acknowledged: true, status: 'Acknowledged' } : alert
        )
      )
    } catch (error) {
      console.error('Error acknowledging alert:', error)
    }
  }

  const value = {
    zones,
    alerts,
    systemMetrics,
    isConnected,
    lastUpdate,
    selectedTalukas,
    acknowledgeAlert,
    logs,
    addLog,
    // isDemoRunning: true when demo is active OR when simulator is simply running
    isDemoRunning: simulatorStatus.running,
    demoStep,
    demoMessage,
    demoComplete,
    runDemoScenario,
    stopDemoScenario,
    applyZoneIntervention,
    simulatorStatus,
    refreshData: () => {}
  }

  return <DataContext.Provider value={value}>{children}</DataContext.Provider>
}
